// Package shell spawns an interactive shell bound to a private AZURE_CONFIG_DIR.
package shell

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/spf13/afero"

	"github.com/vietz-dev/azie/internal/azure"
	"github.com/vietz-dev/azie/internal/config"
	"github.com/vietz-dev/azie/internal/session"
)

// %[1]s is replaced with the absolute path of this binary, so the prompt works
// even when azie is not on PATH. AZIE_CTX is refreshed before every prompt so
// in-place switches show up immediately; the context line goes on its own line
// because prompts like starship fill line 1 to the full terminal width.
const fishRC = `
functions --copy fish_prompt __azie_fish_prompt_original
function fish_prompt
    set -gx AZIE_CTX ("%[1]s" info)
    test "$AZIE_PROMPT_DISABLE" = 1; or echo "[$AZIE_CTX]"
    __azie_fish_prompt_original $argv
end
`

const zshRC = `
[[ -f "$HOME/.zshenv" ]] && source "$HOME/.zshenv"
[[ -f "$HOME/.zprofile" ]] && source "$HOME/.zprofile"
[[ -f "$HOME/.zshrc" ]] && source "$HOME/.zshrc"
[[ -f "$HOME/.zlogin" ]] && source "$HOME/.zlogin"
setopt PROMPT_SUBST
autoload -Uz add-zsh-hook
function __azie_precmd() {
    export AZIE_CTX="$("%[1]s" info)"
    [[ "$AZIE_PROMPT_DISABLE" == 1 ]] && return
    local p=$'[$AZIE_CTX]\n'
    [[ "$PS1" != *"$p"* ]] && PS1="$p$PS1"
}
add-zsh-hook precmd __azie_precmd
`

const bashRC = `
[[ -f /etc/profile ]] && source /etc/profile
[[ -f "$HOME/.bash_profile" ]] && source "$HOME/.bash_profile"
[[ -f "$HOME/.bashrc" ]] && source "$HOME/.bashrc"
PROMPT_COMMAND='export AZIE_CTX="$("%[1]s" info)"'"${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
[[ "$AZIE_PROMPT_DISABLE" == 1 ]] || PS1='[$AZIE_CTX]\n'"$PS1"
`

// detectShell returns AZIE_SHELL, else the configured shell, else the shell
// azie was started from (parent process, like kubie), else $SHELL.
func detectShell(configured string) string {
	if s := os.Getenv("AZIE_SHELL"); s != "" {
		return s
	}
	if configured != "" {
		return configured
	}
	out, err := exec.Command("ps", "-o", "comm=", "-p", strconv.Itoa(os.Getppid())).Output() //nolint:gosec // pid is ours
	if err == nil {
		switch p := filepath.Base(strings.TrimPrefix(strings.TrimSpace(string(out)), "-")); p {
		case "fish", "zsh", "bash":
			return p
		}
	}
	return filepath.Base(os.Getenv("SHELL"))
}

// Spawn starts an interactive shell with AZURE_CONFIG_DIR pointing at a
// private copy of ~/.azure, so login and subscription are scoped to that shell.
// A non-empty group becomes the default resource group of that shell.
func Spawn(fs afero.Fs, cfg config.Settings, sub azure.Subscription, group string) error {
	tmp, err := afero.TempDir(fs, "", "azie-")
	if err != nil {
		return err
	}
	defer func() { _ = fs.RemoveAll(tmp) }()

	if err := azure.CopyConfig(fs, azure.Home(), tmp); err != nil {
		return err
	}
	p, err := azure.ReadProfile(fs, tmp)
	if err != nil {
		return err
	}
	p.SetDefault(sub.ID)
	if err := p.Write(fs, tmp); err != nil {
		return err
	}
	if group != "" {
		if err := azure.SetDefaultGroup(fs, tmp, group); err != nil {
			return err
		}
	}
	// Seed the history so `azie ctx -` / `azie rg -` know where the shell started.
	if err := (session.Session{Ctx: []string{sub.Name}, Rg: []string{azure.DefaultGroup(fs, tmp)}}).Save(fs, tmp); err != nil {
		return err
	}

	self, err := os.Executable()
	if err != nil {
		return err
	}
	// The rc constants end with a newline, so the start hook is appended as is.
	start := cfg.Hooks.StartCtx
	fishRC, zshRC, bashRC := fmt.Sprintf(fishRC, self)+start, fmt.Sprintf(zshRC, self)+start, fmt.Sprintf(bashRC, self)+start

	shell := detectShell(cfg.Shell)
	var cmd *exec.Cmd
	env := append(os.Environ(), "AZURE_CONFIG_DIR="+tmp, "AZIE_ACTIVE=1")
	if cfg.Prompt.Disable {
		env = append(env, "AZIE_PROMPT_DISABLE=1")
	}
	switch shell {
	case "fish":
		cmd = exec.Command("fish", "-iC", fishRC) //nolint:gosec // rc script is generated by us
	case "zsh":
		// ponytail: user ZDOTDIR override and /etc/zsh* files not handled; see kubie/src/shell/zsh.rs if needed.
		if err := afero.WriteFile(fs, filepath.Join(tmp, ".zshrc"), []byte(zshRC), 0o600); err != nil {
			return err
		}
		env = append(env, "ZDOTDIR="+tmp)
		cmd = exec.Command("zsh", "-i")
	case "bash":
		rc := filepath.Join(tmp, "azie.bashrc")
		if err := afero.WriteFile(fs, rc, []byte(bashRC), 0o600); err != nil {
			return err
		}
		cmd = exec.Command("bash", "--rcfile", rc) //nolint:gosec // rc file is generated by us
	default:
		return fmt.Errorf("unsupported shell %q (set AZIE_SHELL to fish, zsh or bash)", shell)
	}
	cmd.Env = env
	cmd.Stdin, cmd.Stdout, cmd.Stderr = os.Stdin, os.Stdout, os.Stderr
	var exit *exec.ExitError
	if err := cmd.Run(); err != nil && !errors.As(err, &exit) {
		return err
	}
	// A non-zero shell exit is not our problem. The stop hook runs with the same env
	// while the temp config dir still exists.
	if cfg.Hooks.StopCtx == "" {
		return nil
	}
	hook := exec.Command(shell, "-c", cfg.Hooks.StopCtx) //nolint:gosec // snippet comes from the user's own settings file
	hook.Env = env
	hook.Stdin, hook.Stdout, hook.Stderr = os.Stdin, os.Stdout, os.Stderr
	return hook.Run()
}
